// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: app-mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/doc-bang.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/doc-bang.ts
var fail = (text) => ({ content: [{ type: "text", text }], isError: true });
async function docBang(ctx, table, limit2, order) {
  if (!ctx.isAuthenticated()) return fail("Not authenticated");
  let q = supabaseForUser(ctx).from(table).select("*").limit(limit2);
  if (order) q = q.order(order, { ascending: false });
  const { data, error } = await q;
  if (error) return fail(error.message);
  return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
}
var limit = { limit: z.number().int().min(1).max(100).default(20).describe("Max rows to return.") };
var ro = { readOnlyHint: true, idempotentHint: true, openWorldHint: false };
var listCompanies = defineTool({
  name: "list_companies",
  title: "List companies",
  description: "List the businesses owned by the signed-in user.",
  inputSchema: limit,
  annotations: ro,
  handler: ({ limit: limit2 }, ctx) => docBang(ctx, "companies", limit2)
});
var listInvoices = defineTool({
  name: "list_invoices",
  title: "List invoices",
  description: "List the signed-in user's most recent invoices.",
  inputSchema: limit,
  annotations: ro,
  handler: ({ limit: limit2 }, ctx) => docBang(ctx, "invoices", limit2, "created_at")
});
var listTransactions = defineTool({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's most recent bank transactions.",
  inputSchema: limit,
  annotations: ro,
  handler: ({ limit: limit2 }, ctx) => docBang(ctx, "transactions", limit2, "created_at")
});

// src/lib/mcp/index.ts
var projectRef = "onhkrgmhltrhhmabzgzn";
var mcp_default = defineMcp({
  name: "kapiva-capital-flow",
  title: "KAPIVA Capital Flow",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's MIMI Wallet data: companies, invoices and bank transactions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listCompanies, listInvoices, listTransactions]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "app-mcp" }));
