-- Separate generated demo transactions from real bank statements.
--
-- The mock "connect a bank" button writes rows straight into `transactions`,
-- the same table Cas syncs into. Once a real account was linked, a dashboard
-- for one company was adding ₫497M of invented income to ₫9M of real income and
-- presenting the sum as that company's cash flow. Nothing on screen could tell
-- them apart.
--
-- That matters more here than it would elsewhere: the 1 tỷ/năm exemption
-- threshold is decided by revenue, and a few fabricated rows move a household
-- across it.
--
-- The demo path stays — judges and investors need something to look at without
-- a bank account — but its output is now labelled and excluded from every
-- figure that claims to describe the business.

ALTER TABLE public.transactions
  ADD COLUMN IF NOT EXISTS is_synthetic boolean NOT NULL DEFAULT false;

-- generateMockTransactions builds `TXN{bankCode}{Date.now()}{i}`; Cas rows are
-- prefixed `bankhub:` and SePay `sepay:`. Matching the prefix is exact, so this
-- needs no guessing about amounts or merchant names.
UPDATE public.transactions
SET is_synthetic = true
WHERE reference_id LIKE 'TXN%'
  AND is_synthetic = false;

-- Read on every dashboard load, always alongside company_id.
CREATE INDEX IF NOT EXISTS transactions_company_synthetic_idx
  ON public.transactions (company_id, is_synthetic);

COMMENT ON COLUMN public.transactions.is_synthetic IS
  'Generated by the demo connector, not from a bank. Must be excluded from any figure presented as the business''s own.';
